### ISSUE TITLE
command() hangs with default config on OSX w/MacPorts Vim

### ISSUE THREAD

**Issue by fweep** [AndrewRadev/vimrunner#17]
I'm using Vimrunner under OSX, and it's hanging on `start` with `vim`.  I can manually start and interact with a server as expected from the command line.  The specs/config I'm using work fine in Linux.

I was able to get it working with MacPorts's `mvim`, which is just a wrapper around MacVim.  Unfortunately, that isn't a headless configuration, so it's not a viable long-term solution.

I've created a gist with [config details](https://gist.github.com/fweep/5241832), including the output of both `vim --version` and `mvim --version`.  I'd be happy to help test/track this down, but before I dive in there, do you have any ideas?  I've already read all of https://github.com/AndrewRadev/vimrunner/issues/11, which is how I got this far.

Thanks for the gem!  This has really changed how I write plugins.

**Comment by AndrewRadev** [comment]
Since I can't really debug this issue effectively, and it's been a while, I guess I'll go ahead and close it for the moment.
