### ISSUE TITLE
When used with RSpec, OS X Mountain Lion kernel panics

### ISSUE THREAD

**Issue by moll** [AndrewRadev/vimrunner#29]
That's a bit of a crazy issue and quite definitely not the fault of Vimrunner, but checking to see if anyone else experiences something similar and whether they've found a workaround.

With the following `.rspec` file:
```
--default-path test
--pattern test/**/*_test.rb
--require ./test/rspec
```

And with the following `test/rspec.rb` file:
```
require "vimrunner"

RSpec.configure do |config|
  config.before(:suite) do
    @vim = Vimrunner.start
  end

  config.after(:suite) do
    @vim.kill if @vim
  end
end
```

Every time I run `rspec`, the kernel panics with `negative open count` and lists Vim as the process. Running `vimrunner` on the command line itself does not.

**Comment by AndrewRadev** [comment]
It's been a while, and it doesn't seem like there's anybody out there that could help :). I'll go ahead and close this issue, since there's not much I can do about it.
