### ISSUE TITLE
Doesn't select padding

### ISSUE THREAD

**Issue by hgiesel** [AndrewRadev/vimrunner#43]
Given: I open Vimrunner and create a sample document:
```ruby
require 'vimrunner'
vim = Vimrunner.start
vim.insert 'foo(   asdf   );'
vim.normal 'Fa'
```

When: I execute `vim.normal 'yib'; vim.command 'echo getreg(\'"\')';`
Then: I expect an output of `␣␣␣asdf␣␣␣`.
However: I get an output of `asdf` (without the padding).

Tested under:
vimrunner (0.3.1)

**Comment by AndrewRadev** [comment]
I should have realized a long time ago that running `strip` on the output would be an issue for a situation like this :). I've applied a fix to master. Could you try it out and let me know if it works for you? I'll cut a new version afterwards.

**Comment by hgiesel** [comment]
Yes, it works now, thanks very much. Great project by the way!
