### ISSUE TITLE
How to expose the functions for unit-testing

### ISSUE THREAD

**Issue by Sathors** [AndrewRadev/vimrunner#44]
Hi,

is there a way to access the script functions from the tests?

I have read that instead of calling my functions s:MyFunction(), I could expose them with MyPlugin#MyFunction(), but I don't seem to get that working. All my plugin definition resides within "plugin/my_plugin.vim".

Thanks for the great work!

**Comment by AndrewRadev** [comment]
Thank you for the kind words :)

Functions that start with `s:` are script-local functions. Reading up on [`:help s:var`](http://vimhelp.appspot.com/eval.txt.html#s%3avar) will give you a lot more context.

In effect, those functions are "private" for this script. It might be possible to use some fancy tricks to call them, but it's complicated and I wouldn't bother. 

As you point out, it's a much better idea to expose them with `MyPlugin#MyFunction()`. That way, they're namespaced with your plugin name, but they're still callable. You can consider those the "public interface" of your plugin. You also get the benefit of lazy-loading for them. 

You can get more information on it with [`:help autoload`](http://vimhelp.appspot.com/eval.txt.html#autoload), but the short version is that a function called `foo#bar#baz()` should live in the file `autoload/foo/bar.vim` within your plugin. Here's an example of how I do it in one of my plugins: https://github.com/AndrewRadev/writable_search.vim/blob/a8bcdefddd16b29f57e18298f0b182ae9691cf1e/autoload/writable_search/command.vim. Note that I also have `s:` functions which are just helpers that I only use in this file, so I wouldn't test them.

After you've exposed your functions, you could call them with `vim.command('call some#function()')`, or you could get their output with `vim.echo('some#function()')`. In general, I use Vimrunner as more of an integration testing helper, so I don't directly test functions -- I do stuff like write in a file, run mappings or commands, and then expect the results to be what I expect them to be. But, feel free to try out different options for yourself. 

Some very recent version of Vim also have special functions like `assert_equal()` that are intended to be used with testing, but I haven't really experimented with them. The full list can be found at [`:help test-functions`](http://vimhelp.appspot.com/usr_41.txt.html#test%2dfunctions)

**Comment by Sathors** [comment]
Hi @AndrewRadev.

Thank you for the detailed explanation.

And there is no way to use some#function, without having to put every function in its own file using the autoload/plugin/function.vim? Because I have many small functions, and I would prefer to have all of them in the same file if it would be possible, else it will lead to too much fragmentation.

I will read more about it though, to see if I can find what I am looking for.

**Comment by AndrewRadev** [comment]
You don't have to put every file in its own function. If you look at the example I linked to, you might notice there's several functions in the same file. It's one file per *namespace*. In fact, you can easily put all of your functions in a file called `autoload/myplugin.vim`, under `myplugin#FunctionName`.

But yeah, it's best if you go through the documentation yourself, you'll figure it out :).

**Comment by Sathors** [comment]
Thanks @AndrewRadev, as you mentioned its only one file, so I guess that there will not be fragmentation.

I think I will have a file plugin/my_plugin.vim, with a mapping calling a my_plugin#function.
Triggering the mapping will autoload the autoload/my_plugin.vim, where my_plugin#function will be defined, along with all the helper functions it needs.

Thank you once more for your help!
